//UOLib/UWorldItem.pas

namespace Shared;

//TWorldItem
public abstract class WorldItem : MulBlock, IComparable<WorldItem> {
    protected bool _locked;
    protected WorldBlock? _owner;
    protected bool _selected;

    protected ushort _tileId;
    protected ushort _x;
    protected ushort _y;
    protected sbyte _z;

    public WorldItem(WorldBlock? owner) {
        Selected = false;
        Locked = false;
        Owner = owner;
    }

    public WorldBlock? Owner {
        get => _owner;
        set {
            if (_owner != value) {
                if (_owner != null) {
                    _owner.Changed = true;
                    if (Locked) _owner.RemoveRef();
                    if (Selected) _owner.RemoveRef();
                }

                _owner = value;
                if (_owner != null) {
                    _owner.Changed = true;
                    if (Locked) _owner.AddRef();
                    if (Selected) _owner.AddRef();
                }
            }
        }
    }

    public virtual ushort TileId {
        get => RawTileId;
        set {
            if (RawTileId != value) {
                RawTileId = value;
                DoChanged();
            }
        }
    }

    public ushort X {
        get => _x;
        set {
            if (_x != value) {
                _x = value;
                DoChanged();
            }
        }
    }

    public ushort Y {
        get => _y;
        set {
            if (_y != value) {
                _y = value;
                DoChanged();
            }
        }
    }

    public virtual sbyte Z {
        get => RawZ;
        set {
            if (RawZ != value) {
                RawZ = value;
                DoChanged();
            }
        }
    }

    public bool Selected {
        get => _selected;
        set {
            if (Owner != null && _selected != value) {
                if (value) Owner.AddRef();
                else Owner.RemoveRef();
            }

            _selected = value;
        }
    }

    public bool CanBeEdited { get; set; }

    public bool Locked {
        get => _locked;
        set {
            if (_locked != value) {
                _locked = value;
                if (Owner != null) {
                    if (_locked)
                        Owner.AddRef();
                    else
                        Owner.RemoveRef();
                }
            }
        }
    }

    public int Priority { get; set; }
    public sbyte PriorityBonus { get; set; }
    public int PrioritySolver { get; set; }

    public ushort RawTileId {
        get => _tileId;
        private set => _tileId = value;
    }

    public sbyte RawZ {
        get => _z;
        private set => _z = value;
    }

    //Can we replace some with autogenerated one?
    public int CompareTo(WorldItem? other) {
        if (ReferenceEquals(this, other)) return 0;
        if (ReferenceEquals(null, other)) return 1;

        if (X != other.X) return X - other.X;
        if (Y != other.Y) return Y - other.Y;
        var result = Priority.CompareTo(other.Priority);
        if (result != 0) {
            if (this is MapCell && other is StaticItem) return -1;
            if (this is StaticItem && other is MapCell) return 1;
            if (this is MapCell && other is WorldItem) return -1;
            if (this is WorldItem && other is MapCell) return 1;
        }

        return PrioritySolver - other.PrioritySolver;
    }

    protected void DoChanged() {
        if (Owner != null) Owner.Changed = true;
    }

    public void UpdatePos(ushort x, ushort y, sbyte z) {
        _x = x;
        _y = y;
        RawZ = z;
        DoChanged();
    }

    public void Delete() {
        Selected = false;
        Locked = false;
        DoChanged();
    }
}